version: '2.1'
services:
  nginx:
    restart: always
    container_name: ezf_nginx
    build: ./nginx/
    ports:
      - 80:80
    links:
      - ezf_notifications
      - ezf_builder
      - ezf_user
      - ezf_academy
      - ezf_funnels
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ez-builder.conf:/etc/nginx/conf.d/ez-builder.conf
      - ./nginx/ez-notifications.conf:/etc/nginx/conf.d/ez-notifications.conf
      - ./nginx/ez-user.conf:/etc/nginx/conf.d/ez-user.conf
      - ./nginx/ez-academy.conf:/etc/nginx/conf.d/ez-academy.conf
      - ./nginx/ez-funnels.conf:/etc/nginx/conf.d/ez-funnels.conf
      - ./logs/nginx:/var/log/nginx

  ezf_builder:
    container_name: ezf_builder
    restart: "no"
    image: thecodingmachine/php:7.2-v2-fpm
    volumes:
      - ../ez-builder:/var/www/html/ez-builder
      - $SSH_AUTH_SOCK:/ssh-agent
      - ../:/var/www/html/ez-builder/data/source
    working_dir: /var/www/html/ez-builder
    environment:
      SSH_AUTH_SOCK: /ssh-agent
      PHP_EXTENSION_GD: 1
      PHP_EXTENSION_APCU: 1
      PHP_EXTENSION_BCMATH: 1
      PHP_EXTENSION_SOAP: 1
      PHP_EXTENSION_INTL: 1
      PHP_EXTENSION_YAML: 1
      PHP_EXTENSION_PDO_PGSQL: 1
      PHP_EXTENSION_SOCKETS: 1

      PHP_EXTENSION_XDEBUG: $DOCKER_BLACKFIRE_ENABLED
      PHP_INI_XDEBUG__REMOTE_PORT: 9000
      PHP_IDE_CONFIG: "serverName=ezf_builder"
      XDEBUG_CONFIG: "remote_port=9000 remote_autostart=1"

      PHP_EXTENSION_BLACKFIRE: $DOCKER_BLACKFIRE_ENABLED
      BLACKFIRE_AGENT: blackfire

    links:
      - redis
      - mysql
      - rabbitmq
      - postgres
      - hotcoder_tunnel
      - blackfire
    external_links:
      - nginx:api.builder.testing.ezf.develop

  ezf_notifications:
    container_name: ezf_notifications
    restart: "no"
    image: thecodingmachine/php:7.2-v2-fpm
    volumes:
      - ../ez-notifications:/var/www/html/ez-notifications
      - $SSH_AUTH_SOCK:/ssh-agent
      - ../:/var/www/html/ez-notifications/data/source
    working_dir: /var/www/html/ez-notifications
    environment:
      SSH_AUTH_SOCK: /ssh-agent
      PHP_EXTENSION_GD: 1
      PHP_EXTENSION_APCU: 1
      PHP_EXTENSION_BCMATH: 1
      PHP_EXTENSION_SOAP: 1
      PHP_EXTENSION_INTL: 1
      PHP_EXTENSION_YAML: 1
      PHP_EXTENSION_PDO_PGSQL: 1
      PHP_INI_XDEBUG__REMOTE_PORT: 9000

      PHP_EXTENSION_XDEBUG: $DOCKER_BLACKFIRE_ENABLED
      PHP_IDE_CONFIG: "serverName=ezf_notifications"
      XDEBUG_CONFIG: "remote_port=9000 remote_autostart=1"

      PHP_EXTENSION_BLACKFIRE: $DOCKER_BLACKFIRE_ENABLED
      BLACKFIRE_AGENT: blackfire

      STARTUP_COMMAND_1: sudo apt-get install -y ssmtp
      STARTUP_COMMAND_2: sudo chmod 777 /etc/ssmtp/ssmtp.conf && sudo touch /usr/local/etc/php/conf.d/mail.ini && sudo chmod 777 /usr/local/etc/php/conf.d/mail.ini
      STARTUP_COMMAND_3: echo "FromLineOverride=YES" >> /etc/ssmtp/ssmtp.conf && echo 'sendmail_path = "/usr/sbin/ssmtp -t"' > /usr/local/etc/php/conf.d/mail.ini
    links:
      - redis
      - mysql
      - rabbitmq
      - postgres
      - hotcoder_tunnel
      - blackfire
    external_links:
      - nginx:api.notifications.testing.ezf.develop

  ezf_user:
    container_name: ezf_user
    restart: "no"
    image: thecodingmachine/php:7.2-v2-fpm
    volumes:
      - ../ez-user:/var/www/html/ez-user
      - $SSH_AUTH_SOCK:/ssh-agent
      - ../:/var/www/html/ez-user/data/source
    working_dir: /var/www/html/ez-user
    environment:
      SSH_AUTH_SOCK: /ssh-agent
      PHP_EXTENSION_GD: 1
      PHP_EXTENSION_APCU: 1
      PHP_EXTENSION_BCMATH: 1
      PHP_EXTENSION_SOAP: 1
      PHP_EXTENSION_INTL: 1
      PHP_EXTENSION_YAML: 1
      PHP_EXTENSION_PDO_PGSQL: 1
      PHP_EXTENSION_SOCKETS: 1

      PHP_EXTENSION_XDEBUG: $DOCKER_BLACKFIRE_ENABLED
      PHP_INI_XDEBUG__REMOTE_PORT: 9000
      PHP_IDE_CONFIG: "serverName=ezf_user"
      XDEBUG_CONFIG: "remote_port=9000 remote_autostart=1"

      PHP_EXTENSION_BLACKFIRE: $DOCKER_BLACKFIRE_ENABLED
      BLACKFIRE_AGENT: blackfire

    links:
      - redis
      - mysql
      - rabbitmq
      - postgres
      - hotcoder_tunnel
      - blackfire
    external_links:
      - nginx:api.user.testing.ezf.develop

  ezf_academy:
    container_name: ezf_academy
    restart: "no"
    image: thecodingmachine/php:7.2-v2-fpm
    volumes:
      - ../ez-academy:/var/www/html/ez-academy
      - $SSH_AUTH_SOCK:/ssh-agent
      - ../:/var/www/html/ez-academy/data/source
    working_dir: /var/www/html/ez-academy
    environment:
      SSH_AUTH_SOCK: /ssh-agent
      PHP_EXTENSION_GD: 1
      PHP_EXTENSION_APCU: 1
      PHP_EXTENSION_BCMATH: 1
      PHP_EXTENSION_SOAP: 1
      PHP_EXTENSION_INTL: 1
      PHP_EXTENSION_YAML: 1
      PHP_EXTENSION_PDO_PGSQL: 1
      PHP_EXTENSION_SOCKETS: 1

      PHP_EXTENSION_XDEBUG: $DOCKER_BLACKFIRE_ENABLED
      PHP_INI_XDEBUG__REMOTE_PORT: 9000
      PHP_IDE_CONFIG: "serverName=ezf_academy"
      XDEBUG_CONFIG: "remote_port=9000 remote_autostart=1"

      PHP_EXTENSION_BLACKFIRE: $DOCKER_BLACKFIRE_ENABLED
      BLACKFIRE_AGENT: blackfire

    links:
      - redis
      - mysql
      - rabbitmq
      - postgres
      - hotcoder_tunnel
      - blackfire
    external_links:
      - nginx:api.academy.testing.ezf.develop

  ezf_funnels:
    container_name: ezf_funnels
    restart: "no"
    image: thecodingmachine/php:7.2-v2-fpm
    volumes:
      - ../ez-funnels:/var/www/html/ez-funnels
      - $SSH_AUTH_SOCK:/ssh-agent
      - ../:/var/www/html/ez-funnels/data/source
    working_dir: /var/www/html/ez-funnels
    environment:
      SSH_AUTH_SOCK: /ssh-agent
      PHP_EXTENSION_GD: 1
      PHP_EXTENSION_APCU: 1
      PHP_EXTENSION_BCMATH: 1
      PHP_EXTENSION_SOAP: 1
      PHP_EXTENSION_INTL: 1
      PHP_EXTENSION_YAML: 1
      PHP_EXTENSION_PDO_PGSQL: 1
      PHP_EXTENSION_SOCKETS: 1

      PHP_EXTENSION_XDEBUG: $DOCKER_BLACKFIRE_ENABLED
      PHP_INI_XDEBUG__REMOTE_PORT: 9000
      PHP_IDE_CONFIG: "serverName=ezf_funnels"
      XDEBUG_CONFIG: "remote_port=9000 remote_autostart=1"

      PHP_EXTENSION_BLACKFIRE: $DOCKER_BLACKFIRE_ENABLED
      BLACKFIRE_AGENT: blackfire

    links:
      - redis
      - mysql
      - rabbitmq
      - postgres
      - hotcoder_tunnel
      - blackfire
    external_links:
      - nginx:api.funnels.testing.ezf.develop

  jad:
    container_name: jad
    restart: "no"
    image: thecodingmachine/php:7.2-v2-fpm
    volumes:
      - ../jad:/var/www/html/jad
      - $SSH_AUTH_SOCK:/ssh-agent
    working_dir: /var/www/html/jad
    environment:
      SSH_AUTH_SOCK: /ssh-agent
      PHP_EXTENSION_GD: 1
      PHP_EXTENSION_APCU: 1
      PHP_EXTENSION_XDEBUG: $DOCKER_BLACKFIRE_ENABLED
      PHP_EXTENSION_BCMATH: 1
      PHP_EXTENSION_SOAP: 1
      PHP_EXTENSION_INTL: 1
      PHP_EXTENSION_YAML: 1
      PHP_EXTENSION_PDO_PGSQL: 1
      PHP_INI_XDEBUG__REMOTE_PORT: 9000
      PHP_IDE_CONFIG: "serverName=jad"
      XDEBUG_CONFIG: "remote_port=9000 remote_autostart=1"
    links:
      - redis
      - mysql
      - rabbitmq
      - postgres

  hotcoder_tunnel:
    image: awful/ssh_supervisord:latest
    build: ./ssh
    container_name: hotcoder_tunnel
    environment:
      SSH_AUTH_SOCK: /ssh-agent
    volumes:
      - $SSH_AUTH_SOCK:/ssh-agent
      - ~/.ssh/:/ssh
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts
      - ./ssh/hotcoder_tunnel/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./logs/supervisord/hotcoder:/var/log/supervisor

  blackfire:
    image: blackfire/blackfire
    container_name: blackfire
    environment:
      BLACKFIRE_CLIENT_ID: $BLACKFIRE_CLIENT_ID
      BLACKFIRE_CLIENT_TOKEN: $BLACKFIRE_CLIENT_TOKEN
      BLACKFIRE_SERVER_ID: $BLACKFIRE_SERVER_ID
      BLACKFIRE_SERVER_TOKEN: $BLACKFIRE_SERVER_TOKEN
      BLACKFIRE_LOG_LEVEL: $BLACKFIRE_LOG_LEVEL

  postgres:
    image: postgres:11.2
    container_name: ezf_postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "6543:5432"
    volumes:
      - ./postgres/runtime/data:/var/lib/postgresql/data
      - ./postgres/init_scripts:/docker-entrypoint-initdb.d/
      - ./logs/postgres:/var/log/postgresql/

  pgadmin:
    image: dpage/pgadmin4:4.5
    container_name: ezf_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "email@dot.com"
      PGADMIN_DEFAULT_PASSWORD: "q1w2e3r4"
    ports:
      - "5050:80"
    links:
      - postgres
    volumes:
      - ./pgadmin/runtime:/var/lib/pgadmin

  mysql:
    container_name: ezf_mysql
    image: mariadb:10.3.14
    ports:
      - 3306:3306
    volumes:
      - ./mysql/runtime:/var/lib/mysql
      - ./mysql/init_scripts:/docker-entrypoint-initdb.d/
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ezf
      MYSQL_PASSWORD: ezf

  phpmyadmin:
    container_name: ezf_pma
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8084:80
    links:
      - mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: secret_password
      PMA_HOST: mysql
      PMA_ARBITRARY: 1

  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: ezf_redis
    restart: "no"
    command: redis-server --requirepass 12345678

  rabbitmq:
    image: rabbitmq:management
    container_name: ezf_rabbit
    restart: "no"
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 8085:15672

  swagger_ui:
    image: swaggerapi/swagger-ui
    container_name: ezf_swagger_ui
    volumes:
      - ../ez-swagger:/usr/share/nginx/html/ez-swagger
    environment:
      API_URL: http://localhost:8081/ez-swagger/ez-contacts.yml
    ports:
      - 8081:8080