version: '2.1'
services:
  nginx:
    restart: always
    container_name: ezf_nginx
    build: ./nginx/
    ports:
      - 80:80
    links:
      - ezf_notifications
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ez-notifications.conf:/etc/nginx/conf.d/ez-notifications.conf
      - ./logs/nginx:/var/log/nginx

  ezf_notifications:
    container_name: ezf_notifications
    restart: "no"
    image: thecodingmachine/php:7.2-v2-fpm
    volumes:
      - ../ez-notifications:/var/www/html/ez-notifications
      - $SSH_AUTH_SOCK:/ssh-agent
      - ../:/var/www/html/ez-notifications/data/source
    working_dir: /var/www/html/ez-notifications
    environment:
      SSH_AUTH_SOCK: /ssh-agent
      PHP_EXTENSION_GD: 1
      PHP_EXTENSION_XDEBUG: 1
      PHP_EXTENSION_BCMATH: 1
      PHP_EXTENSION_SOAP: 1
      PHP_EXTENSION_INTL: 1
      PHP_EXTENSION_YAML: 1
      PHP_EXTENSION_PDO_PGSQL: 1
      PHP_INI_XDEBUG__REMOTE_PORT: 9000
      PHP_IDE_CONFIG: "serverName=ezf_notifications"
      XDEBUG_CONFIG: "remote_port=9000 remote_autostart=1"
      STARTUP_COMMAND_1: sudo apt-get install -y ssmtp
      STARTUP_COMMAND_2: sudo chmod 777 /etc/ssmtp/ssmtp.conf && sudo touch /usr/local/etc/php/conf.d/mail.ini && sudo chmod 777 /usr/local/etc/php/conf.d/mail.ini
      STARTUP_COMMAND_3: echo "FromLineOverride=YES" >> /etc/ssmtp/ssmtp.conf && echo 'sendmail_path = "/usr/sbin/ssmtp -t"' > /usr/local/etc/php/conf.d/mail.ini
    links:
      - redis
      - mysql
      - rabbitmq
      - postgres
    external_links:
      - nginx:api.notifications.testing.ezf.develop

  postgres:
    image: postgres:11.2
    container_name: ezf_postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "6543:5432"
    volumes:
      - ./postgres/runtime/data:/var/lib/postgresql/data
      - ./postgres/init_scripts:/docker-entrypoint-initdb.d/
      - ./logs/postgres:/var/log/postgresql/

  pgadmin:
    image: dpage/pgadmin4:4.5
    container_name: ezf_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "email@dot.com"
      PGADMIN_DEFAULT_PASSWORD: "q1w2e3r4"
    ports:
      - "5050:80"
    links:
      - postgres

  mysql:
    container_name: ezf_mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql/runtime:/var/lib/mysql
      - ./mysql/init_scripts:/docker-entrypoint-initdb.d/
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ezf
      MYSQL_PASSWORD: ezf

  phpmyadmin:
    container_name: ezf_pma
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8084:80
    links:
      - mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: secret_password
      PMA_HOST: mysql
      PMA_ARBITRARY: 1

  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: ezf_redis
    restart: "no"
    command: redis-server --requirepass 12345678

  rabbitmq:
    image: rabbitmq:management
    container_name: ezf_rabbit
    restart: "no"
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 8085:15672

  swagger_ui:
    image: swaggerapi/swagger-ui
    container_name: ezf_swagger_ui
    volumes:
      - ../ez-swagger:/usr/share/nginx/html/ez-swagger
    environment:
      API_URL: http://localhost:8081/ez-swagger/ez-contacts.yml
    ports:
      - 8081:8080